# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ec631eaf318539da7507e354617247ed0009f2568e3a3059c53899be6d851c0528fb5e603702ce04b53205d0144cbfbaff634acf6bff31cde09d1aac853ea5b

test:
  secret_key_base: ad6fd2cf4b3e7667ff4c6eb3b881cff1c88d8f5992db1fd485661d01bc3f3095832ba93bbfbbbcd8c2e3d86bf6334eda4d848f5b04c200ba204c8531d640ccd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
